"""add_missing_phase6_models

Revision ID: bd42a19b945f
Revises: aa12f9c4d5e6
Create Date: 2026-03-30 11:30:23.884097

"""
from typing import Sequence, Union

from alembic import context
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd42a19b945f'
down_revision: Union[str, Sequence[str], None] = 'aa12f9c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usersettings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('theme', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('sms_notifications', sa.Boolean(), nullable=False),
    sa.Column('push_notifications', sa.Boolean(), nullable=False),
    sa.Column('custom_prefs', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usersettings_user_id'), 'usersettings', ['user_id'], unique=True)
    op.create_table('timetable',
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('end_time', sa.String(), nullable=False),
    sa.Column('room', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aichatsession',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aichatsession_student_id'), 'aichatsession', ['student_id'], unique=False)
    op.create_table('learningtask',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('task_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aichatmessage',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['aichatsession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aichatmessage_session_id'), 'aichatmessage', ['session_id'], unique=False)
    op.add_column('aiinsight', sa.Column('context_hash', sa.String(), nullable=True))
    op.add_column('aiinsight', sa.Column('user_rating', sa.Integer(), nullable=True))
    op.add_column('aiinsight', sa.Column('feedback_text', sa.String(), nullable=True))
    op.add_column('aiinsight', sa.Column('prompt_version', sa.String(), server_default='v1.0', nullable=False))
    op.add_column('aiinsight', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('aiinsight', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('aiinsight', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('aiinsight', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    if context.get_context().dialect.name == "sqlite":
        with op.batch_alter_table("aiinsight") as batch_op:
            batch_op.drop_constraint(op.f('aiinsight_student_id_key'), type_='unique')
    else:
        op.drop_constraint(op.f('aiinsight_student_id_key'), 'aiinsight', type_='unique')
    op.create_index(op.f('ix_aiinsight_context_hash'), 'aiinsight', ['context_hash'], unique=False)
    op.create_index(op.f('ix_aiinsight_student_id'), 'aiinsight', ['student_id'], unique=False)
    op.drop_column('aiinsight', 'last_updated')
    op.add_column('api_request_log', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('api_request_log', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('api_request_log', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.add_column('attendance', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('attendance', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('attendance', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('attendance', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    if context.get_context().dialect.name == "sqlite":
        with op.batch_alter_table("attendance") as batch_op:
            batch_op.create_unique_constraint('uq_attendance_student_date', ['student_id', 'date'])
    else:
        op.create_unique_constraint('uq_attendance_student_date', 'attendance', ['student_id', 'date'])
    op.add_column('auditlog', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('auditlog', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('auditlog', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.add_column('chain', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('chain', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('chain', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('chain', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.add_column('class', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('class', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('class', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('class', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.add_column('device_token', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('device_token', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('device_token', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.add_column('exam', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('exam', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('exam', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('exam', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_exam_section_exam_date'), table_name='exam')
    op.add_column('idempotency_key', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('idempotency_key', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('idempotency_key', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.add_column('mark', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('mark', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('mark', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('mark', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_mark_student_exam_subject'), table_name='mark')
    op.create_index('ix_mark_exam_subject', 'mark', ['exam_id', 'subject_id'], unique=False)
    op.create_index('ix_mark_student_subject', 'mark', ['student_id', 'subject_id'], unique=False)
    if context.get_context().dialect.name == "sqlite":
        with op.batch_alter_table("mark") as batch_op:
            batch_op.create_unique_constraint('uq_mark_exam_student_subject', ['exam_id', 'student_id', 'subject_id'])
    else:
        op.create_unique_constraint('uq_mark_exam_student_subject', 'mark', ['exam_id', 'student_id', 'subject_id'])
    op.add_column('notification', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('notification', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('notification', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notification', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.add_column('notification_event', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('notification_event', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('notification_event', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.add_column('otpsession', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('otpsession', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('otpsession', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_otpsession_phone_created_at'), table_name='otpsession')
    op.add_column('outbox_job', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('outbox_job', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('outbox_job', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.add_column('reportcard', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('reportcard', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('reportcard', 'generated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reportcard', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('reportcard', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_reportcard_student_generated_at'), table_name='reportcard')
    op.add_column('school', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('school', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('school', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('school', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.add_column('section', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('section', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('section', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('section', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.add_column('student', sa.Column('parent_joining_code', sa.String(), nullable=True))
    op.add_column('student', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('student', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('student', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('student', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_student_parent_joining_code'), 'student', ['parent_joining_code'], unique=True)
    op.add_column('subject', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('subject', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('subject', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('subject', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.add_column('user', sa.Column('username', sa.String(), nullable=True))
    op.add_column('user', sa.Column('password_hash', sa.String(), nullable=True))
    op.add_column('user', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('user', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('user', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.add_column('user_notification', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('user_notification', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('user_notification', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_notification', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('user_notification', 'deleted_at')
    op.drop_column('user_notification', 'is_deleted')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.alter_column('user', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('user', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('user', 'deleted_at')
    op.drop_column('user', 'is_deleted')
    op.drop_column('user', 'password_hash')
    op.drop_column('user', 'username')
    op.alter_column('subject', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('subject', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('subject', 'deleted_at')
    op.drop_column('subject', 'is_deleted')
    op.drop_index(op.f('ix_student_parent_joining_code'), table_name='student')
    op.alter_column('student', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('student', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('student', 'deleted_at')
    op.drop_column('student', 'is_deleted')
    op.drop_column('student', 'parent_joining_code')
    op.alter_column('section', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('section', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('section', 'deleted_at')
    op.drop_column('section', 'is_deleted')
    op.alter_column('school', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('school', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('school', 'deleted_at')
    op.drop_column('school', 'is_deleted')
    op.create_index(op.f('ix_reportcard_student_generated_at'), 'reportcard', ['student_id', 'generated_at'], unique=False)
    op.alter_column('reportcard', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('reportcard', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('reportcard', 'generated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('reportcard', 'deleted_at')
    op.drop_column('reportcard', 'is_deleted')
    op.alter_column('outbox_job', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('outbox_job', 'deleted_at')
    op.drop_column('outbox_job', 'is_deleted')
    op.create_index(op.f('ix_otpsession_phone_created_at'), 'otpsession', ['phone', 'created_at'], unique=False)
    op.alter_column('otpsession', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('otpsession', 'deleted_at')
    op.drop_column('otpsession', 'is_deleted')
    op.alter_column('notification_event', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('notification_event', 'deleted_at')
    op.drop_column('notification_event', 'is_deleted')
    op.alter_column('notification', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('notification', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('notification', 'deleted_at')
    op.drop_column('notification', 'is_deleted')
    if context.get_context().dialect.name == "sqlite":
        with op.batch_alter_table("mark") as batch_op:
            batch_op.drop_constraint('uq_mark_exam_student_subject', type_='unique')
    else:
        op.drop_constraint('uq_mark_exam_student_subject', 'mark', type_='unique')
    op.drop_index('ix_mark_student_subject', table_name='mark')
    op.drop_index('ix_mark_exam_subject', table_name='mark')
    op.create_index(op.f('ix_mark_student_exam_subject'), 'mark', ['student_id', 'exam_id', 'subject_id'], unique=False)
    op.alter_column('mark', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('mark', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('mark', 'deleted_at')
    op.drop_column('mark', 'is_deleted')
    op.alter_column('idempotency_key', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('idempotency_key', 'deleted_at')
    op.drop_column('idempotency_key', 'is_deleted')
    op.create_index(op.f('ix_exam_section_exam_date'), 'exam', ['section_id', 'exam_date'], unique=False)
    op.alter_column('exam', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('exam', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('exam', 'deleted_at')
    op.drop_column('exam', 'is_deleted')
    op.alter_column('device_token', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('device_token', 'deleted_at')
    op.drop_column('device_token', 'is_deleted')
    op.alter_column('class', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('class', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('class', 'deleted_at')
    op.drop_column('class', 'is_deleted')
    op.alter_column('chain', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('chain', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('chain', 'deleted_at')
    op.drop_column('chain', 'is_deleted')
    op.alter_column('auditlog', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('auditlog', 'deleted_at')
    op.drop_column('auditlog', 'is_deleted')
    if context.get_context().dialect.name == "sqlite":
        with op.batch_alter_table("attendance") as batch_op:
            batch_op.drop_constraint('uq_attendance_student_date', type_='unique')
    else:
        op.drop_constraint('uq_attendance_student_date', 'attendance', type_='unique')
    op.alter_column('attendance', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('attendance', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('attendance', 'deleted_at')
    op.drop_column('attendance', 'is_deleted')
    op.alter_column('api_request_log', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('api_request_log', 'deleted_at')
    op.drop_column('api_request_log', 'is_deleted')
    op.add_column('aiinsight', sa.Column('last_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_aiinsight_student_id'), table_name='aiinsight')
    op.drop_index(op.f('ix_aiinsight_context_hash'), table_name='aiinsight')
    if context.get_context().dialect.name == "sqlite":
        with op.batch_alter_table("aiinsight") as batch_op:
            batch_op.create_unique_constraint(op.f('aiinsight_student_id_key'), ['student_id'])
    else:
        op.create_unique_constraint(op.f('aiinsight_student_id_key'), 'aiinsight', ['student_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('aiinsight', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('aiinsight', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('aiinsight', 'deleted_at')
    op.drop_column('aiinsight', 'is_deleted')
    op.drop_column('aiinsight', 'prompt_version')
    op.drop_column('aiinsight', 'feedback_text')
    op.drop_column('aiinsight', 'user_rating')
    op.drop_column('aiinsight', 'context_hash')
    op.drop_index(op.f('ix_aichatmessage_session_id'), table_name='aichatmessage')
    op.drop_table('aichatmessage')
    op.drop_table('learningtask')
    op.drop_index(op.f('ix_aichatsession_student_id'), table_name='aichatsession')
    op.drop_table('aichatsession')
    op.drop_table('timetable')
    op.drop_index(op.f('ix_usersettings_user_id'), table_name='usersettings')
    op.drop_table('usersettings')
    # ### end Alembic commands ###
