"""Add is_completed to exam

Revision ID: f2ce8a4511aa
Revises: d1e2f3a4b5c6
Create Date: 2026-04-25 15:42:55.732213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2ce8a4511aa'
down_revision: Union[str, Sequence[str], None] = 'd1e2f3a4b5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homework',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homework_section_id'), 'homework', ['section_id'], unique=False)
    op.create_index(op.f('ix_homework_subject_id'), 'homework', ['subject_id'], unique=False)
    op.add_column('exam', sa.Column('is_completed', sa.Boolean(), server_default='false', nullable=False))
    op.drop_column('school', 'phone')
    op.drop_column('school', 'state')
    op.drop_column('school', 'city')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('school', sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('school', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('exam', 'is_completed')
    op.drop_index(op.f('ix_homework_subject_id'), table_name='homework')
    op.drop_index(op.f('ix_homework_section_id'), table_name='homework')
    op.drop_table('homework')
    # ### end Alembic commands ###
